apps/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
	#post views
	#paht('', views.post_list, name='post_list'),
	path('', views.PostListView.as_view(), name='post_list'),
	path('<int:year>/<int:month>/<int:day>/<slug:slug>', views.post_detail, name='post_detail'),
	# path('<int: post_id>/share/', views.post_share, name='post_share'),
]

apps/home/urls.py
from django.urls import path
from home.views import index

app_name = 'home'
urlpatterns = [
    path('', index, name="landing"),
]

apps/product/urls.py
from django.urls import path
from product.views import product_list, product_detail

app_name = 'product'
urlpatterns = [
    path('', product_list, name="product-list"),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', product_detail, name="product-detail")
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap
# from home.sitemaps import PostSitemap

# sitemaps = {
#     'posts': PostSitemap,
# }

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('product/', include('product.urls', namespace='product')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('home.urls', namespace='home')),
    path(
        'about/',
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    path(
        "thanks/",
        TemplateView.as_view(template_name="pages/thanks.html"),
        name="thanks",
    ),
    # path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

apps/home/models.py
from django.db import models

# Create your models here.

class Message(models.Model):
    contact = models.CharField(max_length=100, verbose_name="联系人")
    email = models.EmailField(max_length=150, verbose_name="邮箱")
    message = models.TextField(default="", verbose_name="留言")
    created = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    modified = models.DateTimeField(auto_now=True, verbose_name="修改时间")

    def __str__(self):
        return self.email

apps/home/forms.py
from django import forms


class MessageForm(forms.Form):
    contact = forms.CharField(
        widget = forms.TextInput(
            attrs = {
                "class": "form-control",
                "placeholder": "Your name"
            }
        )
    )
    email = forms.EmailField(
        widget = forms.EmailInput(
            attrs = {
                "class": "form-control",
                "placeholder": "Your email"
            }
        )
    )
    message = forms.CharField(
        widget = forms.Textarea(
            attrs= {
                "class": "form-control",
                "placeholder": "Your message",
                "rows": "4",
            }
        )
    )

apps/home/views.py
from django.shortcuts import render
from .models import Message
from .forms import MessageForm
# Create your views here.

def index(request):
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            contact = form.cleaned_data['contact']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            m = Message(contact = contact, email = email, message = message)
            m.save()
            return  HttpResponseRedirect('/thanks/')
    else:
        form = MessageForm()
    return render(request, 'pages/home.html', {'form': form})

templates/pages/about.html
{% extends "base.html"%}

{% block title %}
About US
{% endblock %}

{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    {# <li class="breadcrumb-item"><a href="{% url 'home:landing'%}">Home</a></li> #}
    <li class="breadcrumb-item active" aria-current="page">About Us</li>
  </ol>
</nav>
This is About Page!
{% endblock %}

templates/pages/blog-detail.html
{% extends 'base.html' %}
{% load blog_tags %}
{% block description %}
    <meta name="description" content="{{ post.description }}">
{% endblock %}
{% block title %}
{{ post.title }}
{% endblock %}
{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'igcae:landing'%}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'blog:post_list'%}">Blog</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ post.title }}</li>
  </ol>
</nav>
<div class="container">
  <div class="row">
    <div class="col-lg-9">

        {{ post.content | safe }}

    </div>
    <aside class="col-lg-3" id="sidebar">
      <h3>Latest Posts</h3>
      {% show_latest_posts 3 %}
    </aside>
  </div>
</div>
{% endblock %}

templates/pages/blog-list.html
{% extends "base.html" %}

{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    {# <li class="breadcrumb-item"><a href="{% url 'igcae:landing'%}">Home</a></li> #}
    <li class="breadcrumb-item active" aria-current="page">Blog</li>
  </ol>
</nav>
<div class="container">
  <div class="row">
    <div class="col-lg-9">
      {% for post in posts %}
      <article class="post-item">
        <div class="">
          <a href="{{ post.get_absolute_url }}"><h2>{{ post.title }}</h2></a>
          <span>{{ post.publish }}</span>
          <p>{{ post.description }}</p>
        </div>
        <div class="cover">
          <img src="" alt="">
        </div>
      </article>
      {% endfor %}
    </div>
    <aside class="col-lg-3">

    </aside>
  </div>
</div>

{% include 'components/pagination.html' with page=page_obj %}
{% endblock %}

templates/pages/home.html
{% extends 'base.html' %}

{% block title %}

{% endblock %}

{% block content %}
This is homepage.
{% endblock %}

templates/pages/product-detail.html
{% extends 'base.html'%}

{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'home:landing'%}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'product:product-list'%}">Product</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{product.name}}</li>
  </ol>
</nav>
<h1>{{ product.name}}</h1>
<p>{{ product.oe }}</p>
{% endblock %}

templates/pages/product-list.html
{% extends 'base.html' %}

{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'home:landing'%}">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Product</li>
  </ol>
</nav>
  <div class="row">
    <div class="col-md-2">
      {% for category in categories %}
      <ul>
        <li><a href="#">{{ category.name }}</a></li>
      </ul>
      {% endfor %}
    </div>
    <div class="col-md-10">
      <div class="product-list d-flex">
        {% for product in products %}
        <article class="product-card">
          <a class="" href="{{ product.get_absolute_url }}">
            <img src="{{product.image.url}}" alt="">
            <h4>{{ product.name }}</h4>
          </a>

        </article>
        {% endfor %}
      </div>
    </div>
  </div>
  {% include 'components/pagination.html' with page=products %}
{% endblock %}